language: ruby
rvm:
- 2.2.4
branches:
  only:
  - source
env:
  global:
    - TMPDIR=/tmp
script: bundle exec jekyll build
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: source
before_install:
- openssl aes-256-cbc -K $encrypted_5474a7e89bab_key -iv $encrypted_5474a7e89bab_iv
  -in deploy_key.enc -out deploy_key -d
