language: ruby
rvm:
- 2.2.4
branches:
  only:
  - source
script: bundle exec jekyll build
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- ssh-add deploy_key
- cat .travis/deploy_key.pem
- git branch -r
before_install:
- openssl aes-256-cbc -K $encrypted_5474a7e89bab_key -iv $encrypted_5474a7e89bab_iv
  -in deploy_key.enc -out deploy_key -d
