language: ruby
rvm:
  - 2.2.4
branches:
  only:
    - source
script: bundle exec jekyll build
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - cat .travis/deploy_key.pem
  - echo $TMPDIR
